services:
  fraud-api:
    build: .
    container_name: fraud-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: fraud-db
    restart: always
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: Lord@7836
      POSTGRES_DB: fraud_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgresuser", "-d", "fraud_db"]
      interval: 5s
      retries: 5
